Migrate from Drone CI to GitHub Action
rancher/system-agent-installer-rke2 pull request #52
Opened 2024-05-17 00:20 UTC by jiaqiluo

This PR migrates the Drone CI to GitHub Action Workflows and cleans up unused scripts. 

The workflow `CI on Releasing Tag` is validated on my fork by using personal: [sample running](https://github.com/jiaqiluo/system-agent-installer-rke2/actions/runs/9120758366) and [the generated image](https://hub.docker.com/layers/jq20/system-agent-installer-rke2/v1.30.0-rc1-rke2r1/images/sha256-4a4cd1523bde549c55e761a3cb64211a671dca3ef45267228519c6312ddbbe38?context=repo)

2024-06-11 16:44 UTC, dereknola approved these changes

2024-06-11 18:12 UTC, brandond approved these changes

2024-06-14 23:50 UTC, brandond requested changes
LGTM, but requesting changes to make sure this is blocked until after the current release is done.

2024-07-01 19:18 UTC, brandond approved these changes

2024-07-01 19:18 UTC, brandond commented
Merging now since the Drone rug has been pulled out from under us.

2024-07-01 19:19 UTC, merged