Data dir rfc pt 2
rancher/system-agent-installer-rke2 pull request #54
Opened 2024-05-22 19:40 UTC by jakefhyde

DO NOT MERGE until May patches are shipped for RKE2. This must go in before June patches in order to be included in the 2.9.0 release of Rancher.

Adds support for configuring the `data-dir` within RKE2.

2024-05-22 19:55 UTC, brandond approved these changes

2024-05-22 19:56 UTC, brandond requested changes

2024-05-22 19:56 UTC, brandond commented on package/Dockerfile
> +ENV RKE2_DATA_DIR=${RKE2_DATA_DIR}
thinking about this more - I don't think this is necessary, is it? The image contents are extracted out to disk by rancher-system-agent and run on the host system. This Docker image is never run, so the args and env vars don't matter.

2024-06-03 21:21 UTC, brandond approved these changes

2024-06-03 21:41 UTC, HarrisonWAffel approved these changes

2024-06-03 21:46 UTC, merged